notice if failed

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,5 +1,7 @@
 #! /bin/bash
 
+SUCCESSFUL_TEST=true
+
 grep_port () {
     echo "Activiating ports:"
     grep -A8 $1 docker-compose.yml | grep -A2 ports | grep "-"
@@ -79,17 +81,32 @@ clense () {
 lint () {
     # Run the functional tests. 
     docker-compose run --rm lint
+
+    if [[ $? -eq 1 ]]; then 
+        SUCCESSFUL_TEST=false
+        echo 'Test failed'
+    fi
 }
 
 unit () {
     # Run the unit tests. 
-    # This includes flake and lenting
+    # This includes flake
     docker-compose run --rm unit
+
+    if [[ $? -eq 1 ]]; then 
+        SUCCESSFUL_TEST=false
+        echo 'Test failed'
+    fi
 }
 
 functional () {
     # Run the functional tests. 
     docker-compose run --rm functional
+
+    if [[ $? -eq 1 ]]; then 
+        SUCCESSFUL_TEST=false
+        echo 'Test failed'
+    fi
 }
 
 tests () {
@@ -98,6 +115,12 @@ tests () {
     lint
     unit
     functional
+    if [[ $SUCCESSFUL_TEST == true ]]
+    then
+        echo 'The tests were successful'
+    else
+        echo 'The tests were unsuccessful'
+    fi
 }
 
 about () {
